/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MeRouteImport } from './routes/me'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StylistRouteImport } from './routes/stylist'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as ApiPublicTmpMakeAdminRouteImport } from './routes/api/public/tmp-make-admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StylistRoute = StylistRouteImport.update({
  id: '/stylist',
  path: '/stylist',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/brands/$slug',
  path: '/brands/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTmpMakeAdminRoute = ApiPublicTmpMakeAdminRouteImport.update({
  id: '/api/public/tmp-make-admin',
  path: '/api/public/tmp-make-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/me': typeof MeRoute
  '/search': typeof SearchRoute
  '/stylist': typeof StylistRoute
  '/wishlist': typeof WishlistRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/brands/': typeof BrandsIndexRoute
  '/api/public/tmp-make-admin': typeof ApiPublicTmpMakeAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/me': typeof MeRoute
  '/search': typeof SearchRoute
  '/stylist': typeof StylistRoute
  '/wishlist': typeof WishlistRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/brands': typeof BrandsIndexRoute
  '/api/public/tmp-make-admin': typeof ApiPublicTmpMakeAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/me': typeof MeRoute
  '/search': typeof SearchRoute
  '/stylist': typeof StylistRoute
  '/wishlist': typeof WishlistRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/brands/': typeof BrandsIndexRoute
  '/api/public/tmp-make-admin': typeof ApiPublicTmpMakeAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/home'
    | '/me'
    | '/search'
    | '/stylist'
    | '/wishlist'
    | '/brands/$slug'
    | '/brands/'
    | '/api/public/tmp-make-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/home'
    | '/me'
    | '/search'
    | '/stylist'
    | '/wishlist'
    | '/brands/$slug'
    | '/brands'
    | '/api/public/tmp-make-admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/home'
    | '/me'
    | '/search'
    | '/stylist'
    | '/wishlist'
    | '/brands/$slug'
    | '/brands/'
    | '/api/public/tmp-make-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  HomeRoute: typeof HomeRoute
  MeRoute: typeof MeRoute
  SearchRoute: typeof SearchRoute
  StylistRoute: typeof StylistRoute
  WishlistRoute: typeof WishlistRoute
  BrandsSlugRoute: typeof BrandsSlugRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  ApiPublicTmpMakeAdminRoute: typeof ApiPublicTmpMakeAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stylist': {
      id: '/stylist'
      path: '/stylist'
      fullPath: '/stylist'
      preLoaderRoute: typeof StylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/brands/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tmp-make-admin': {
      id: '/api/public/tmp-make-admin'
      path: '/api/public/tmp-make-admin'
      fullPath: '/api/public/tmp-make-admin'
      preLoaderRoute: typeof ApiPublicTmpMakeAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  HomeRoute: HomeRoute,
  MeRoute: MeRoute,
  SearchRoute: SearchRoute,
  StylistRoute: StylistRoute,
  WishlistRoute: WishlistRoute,
  BrandsSlugRoute: BrandsSlugRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  ApiPublicTmpMakeAdminRoute: ApiPublicTmpMakeAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
